apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mq-create-tt
  namespace: tekton
spec:
  params:
    - name: highAvailability
    - name: persistence
    - name: clusterName
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: mq-create-pipeline-run-
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
      spec:
        params:
          - name: highAvailability
            value: $(tt.params.highAvailability)
          - name: persistence
            value: $(tt.params.persistence)
          - name: clusterName
            value: $(tt.params.clusterName)
        pipelineRef:
          name: mq-resource-submission
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              metadata:
                creationTimestamp: null
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: ocs-storagecluster-cephfs
                volumeMode: Filesystem
              status: {}
          - name: ssh-credentials
            secret:
              secretName: git-cli-ssh-private-key
          - configMap:
              name: git-data
            name: git-configmap