apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mq-create
  namespace: tekton
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: mq-create-binding
      template:
        ref: mq-create-tt
      name: mq-create
