apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mq-resource-submission
  namespace: tekton
  labels:
    build-name: mq-resource-submission
spec:
  description: |
   This pipeline will be triggered in the event an MQ resource ought to be committed to a cluster.  
  params:
  - name: highAvailability
    type: string
    description: Single or NativeHA.
  - name: persistence
    type: string
    description: Ephemeral or not.
  - name: clusterName
    type: string
    description: The name of the cluster to which MQ should be deployed.
  workspaces:
  - name: shared-data
    description: |
      Shared, persisted data for the tasks constituting this pipeline.
  - name: ssh-credentials
    description: SSH credentials required to perform git commands against select repositories from the Gitops organisation.
  - name: git-configmap
    description: Registry related information housed within said configmap. 
  tasks:
  - name: generate-mq
    taskRef:
      name: generate-mq
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: highAvailability
      value: $(params.highAvailability)
    - name: persistence
      value: $(params.persistence)
  - name: resource-deploy
    runAfter: ["generate-mq"]
    taskRef:
      name: resource-deploy
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: ssh-credentials
    - name: gitops
      workspace: git-configmap
    params:
    - name: verbose
      value: "true"
    - name: clusterName
      value: $(params.clusterName)