kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: tekton

bases:
  - ../../base

patches:
  - target:
      kind: Pipeline
      name: clone
    patch: |-
      - op: replace
        path: /metadata/labels/build-name
        value: "developer-app-deploy"