apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-mq
  namespace: tekton
spec:
  workspaces:
    - description: Output workspace.
      name: output
  params:
    - name: highAvailability
      type: string
      description: Single Instance or NativeHA.
      default: "false"
    - name: persistence
      type: string
      description: Persistent or ephemeral
      default: "false"
  steps:
    - name: mq-generation
      image: quay.io/marwan_attar_ibm/cp4i_mq_generation
      env:
      - name: WORKSPACE
        value: "$(workspaces.output.path)"
      script:  |

        ## TODO: We are depending on global uniqueness given through the cluster name parameter. Enforce check here.
        # Essentially, there should not be any other namespaces created in the Hub cluster with the same name.
        cd /tmp

        # TODO: There should be some parsing logic, and this is a future task. 
        # For purposes of demonstration however this will not be done.
        cp /tmp/mq.yaml $WORKSPACE
        cp /tmp/mqsc.yaml $WORKSPACE
    - name: print-out
      image: quay.io/marwan_attar_ibm/rhacm-install-cluster-deployment-generator
      script: |
        #!/usr/bin/env bash
        ls -ltr /workspace/output
        find /workspace/output -type f -exec cat {} \;