apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-create
  namespace: tekton
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: ace-create-binding
      template:
        ref: ace-create-tt
      name: ace-create
